version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-lint-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn format:check
            - run: yarn lint
            - run: yarn test:ci
            - run: yarn build

workflows:
  build:
    jobs:
      - build-lint-and-test
