version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-lint-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn format:check
            - run: yarn lint
            - run: yarn test:ci
            - run: yarn build

  e2e-test:
    docker:
      - image: cypress/base:12.16.1
        environment:
          DATABASE_URL: postgresql://frodo:friend@localhost:5432/nails_test?schema=public
          
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: frodo
          POSTGRES_DB: nails_test
          POSTGRES_PASSWORD: friend

    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install dockerize
                command: |
                  apk add --no-cache openssl && \
                  DOCKERIZE_VERSION=v0.6.1 wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
                  && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
                  && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            - run: yarn install
            - run: yarn cypress verify
            - run: yarn build
            - run: 
                name: Wait for DB
                command: dockerize -wait tcp://localhost:5432 -timeout 1m
            - run:
                name: Migrate DB
                command: yarn prisma:migrate:up
            - run:
                name: Start webserver
                command: yarn start
                background: true
            - run:
                name: Wait for webserver
                command: yarn wait
            - run:
                name: E2E Cypress tests
                command: yarn e2e:run
          
workflows:
  build:
    jobs:
      - build-lint-and-test
  e2e:
    jobs:
      - e2e-test
